# 10.96.88.71 is CLUSTER_IP of ingress-nginx-controller service
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    sts.hbg.local:53 {
        errors
        cache 30
        hosts {
            10.96.88.71 sts.hbg.local 
            fallthrough
        }
    }
    .:53 {
        errors
        health {
           lameduck 5s
        }
        # rewrite name hello.life.com ingress-nginx-controller.ingress-namespace.svc.cluster.local
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
